package com.github.ttwd80.tigerpayroll.model.entity;


import java.math.BigDecimal;
import java.time.ZonedDateTime;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Allowance generated by hbm2java
 */
@Entity
@Table(name="allowance"
    ,schema="public"
)
public class Allowance  implements java.io.Serializable {


     private Character id;
     private User userByLastModifiedBy;
     private User userByCreatedBy;
     private String name;
     private Integer position;
     private BigDecimal amount;
     private ZonedDateTime createdDate;
     private ZonedDateTime lastModifiedDate;
     private Set<UserAllowance> userAllowances = new HashSet<UserAllowance>(0);

    public Allowance() {
    }

	
    public Allowance(Character id, String name, BigDecimal amount) {
        this.id = id;
        this.name = name;
        this.amount = amount;
    }
    public Allowance(Character id, User userByLastModifiedBy, User userByCreatedBy, String name, Integer position, BigDecimal amount, ZonedDateTime createdDate, ZonedDateTime lastModifiedDate, Set<UserAllowance> userAllowances) {
       this.id = id;
       this.userByLastModifiedBy = userByLastModifiedBy;
       this.userByCreatedBy = userByCreatedBy;
       this.name = name;
       this.position = position;
       this.amount = amount;
       this.createdDate = createdDate;
       this.lastModifiedDate = lastModifiedDate;
       this.userAllowances = userAllowances;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=1)
    public Character getId() {
        return this.id;
    }
    
    public void setId(Character id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="last_modified_by")
    @org.springframework.data.annotation.LastModifiedBy
    public User getUserByLastModifiedBy() {
        return this.userByLastModifiedBy;
    }
    
    public void setUserByLastModifiedBy(User userByLastModifiedBy) {
        this.userByLastModifiedBy = userByLastModifiedBy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="created_by")
    @org.springframework.data.annotation.CreatedBy
    public User getUserByCreatedBy() {
        return this.userByCreatedBy;
    }
    
    public void setUserByCreatedBy(User userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }

    
    @Column(name="name", nullable=false, length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="position")
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }

    
    @Column(name="amount", nullable=false, precision=7)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="created_date", length=35)
    @org.springframework.data.annotation.CreatedDate
    public ZonedDateTime getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(ZonedDateTime createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="last_modified_date", length=35)
    @org.springframework.data.annotation.LastModifiedDate
    public ZonedDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }
    
    public void setLastModifiedDate(ZonedDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="allowance")
    public Set<UserAllowance> getUserAllowances() {
        return this.userAllowances;
    }
    
    public void setUserAllowances(Set<UserAllowance> userAllowances) {
        this.userAllowances = userAllowances;
    }




}


