package com.github.ttwd80.tigerpayroll.model.entity;


import java.time.ZonedDateTime;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BackPayType generated by hbm2java
 */
@Entity
@Table(name="back_pay_type"
    ,schema="public"
)
public class BackPayType  implements java.io.Serializable {


     private Character backPayType;
     private String name;
     private String createdBy;
     private ZonedDateTime createdDate;
     private String lastModifiedBy;
     private ZonedDateTime lastModifiedDate;
     private Set<BackPay> backPays = new HashSet<BackPay>(0);

    public BackPayType() {
    }

	
    public BackPayType(Character backPayType, String name) {
        this.backPayType = backPayType;
        this.name = name;
    }
    public BackPayType(Character backPayType, String name, String createdBy, ZonedDateTime createdDate, String lastModifiedBy, ZonedDateTime lastModifiedDate, Set<BackPay> backPays) {
       this.backPayType = backPayType;
       this.name = name;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.lastModifiedBy = lastModifiedBy;
       this.lastModifiedDate = lastModifiedDate;
       this.backPays = backPays;
    }
   
     @Id 

    
    @Column(name="back_pay_type", unique=true, nullable=false, length=1)
    public Character getBackPayType() {
        return this.backPayType;
    }
    
    public void setBackPayType(Character backPayType) {
        this.backPayType = backPayType;
    }

    
    @Column(name="name", nullable=false, length=20)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="created_by", length=20)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="created_date", length=35)
    @org.springframework.data.annotation.CreatedDate
    public ZonedDateTime getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(ZonedDateTime createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="last_modified_by", length=20)
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }
    
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    
    @Column(name="last_modified_date", length=35)
    @org.springframework.data.annotation.LastModifiedDate
    public ZonedDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }
    
    public void setLastModifiedDate(ZonedDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="backPayType")
    public Set<BackPay> getBackPays() {
        return this.backPays;
    }
    
    public void setBackPays(Set<BackPay> backPays) {
        this.backPays = backPays;
    }




}


