package com.github.ttwd80.tigerpayroll.model.entity;


import java.math.BigDecimal;
import java.time.ZonedDateTime;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,schema="public"
)
public class User  implements java.io.Serializable {


     private String username;
     private Department department;
     private Gender gender;
     private Image image;
     private MaritalStatus maritalStatus;
     private Race race;
     private SocsoStatus socsoStatus;
     private User userByLastModifiedBy;
     private User userByCreatedBy;
     private String fullName;
     private String password;
     private boolean locked;
     private String address;
     private String phoneCell;
     private String phoneOffice;
     private Date dataOfBirth;
     private Date dataJoined;
     private String jobTitle;
     private String qualificationAcademic;
     private String qualificationProfessional;
     private String socsoNo;
     private String epfNo;
     private String incomeTaxNo;
     private BigDecimal basicSalary;
     private ZonedDateTime createdDate;
     private ZonedDateTime lastModifiedDate;
     private Set<Role> rolesForLastModifiedBy = new HashSet<Role>(0);
     private Set<User> usersForLastModifiedBy = new HashSet<User>(0);
     private Set<UserRole> userRolesForLastModifiedBy = new HashSet<UserRole>(0);
     private Set<UserRole> userRolesForUsername = new HashSet<UserRole>(0);
     private Set<User> usersForCreatedBy = new HashSet<User>(0);
     private Set<Image> imagesForCreatedBy = new HashSet<Image>(0);
     private Set<Role> rolesForCreatedBy = new HashSet<Role>(0);
     private Set<Image> imagesForLastModifiedBy = new HashSet<Image>(0);

    public User() {
    }

	
    public User(String username, String fullName, String password, boolean locked, BigDecimal basicSalary) {
        this.username = username;
        this.fullName = fullName;
        this.password = password;
        this.locked = locked;
        this.basicSalary = basicSalary;
    }
    public User(String username, Department department, Gender gender, Image image, MaritalStatus maritalStatus, Race race, SocsoStatus socsoStatus, User userByLastModifiedBy, User userByCreatedBy, String fullName, String password, boolean locked, String address, String phoneCell, String phoneOffice, Date dataOfBirth, Date dataJoined, String jobTitle, String qualificationAcademic, String qualificationProfessional, String socsoNo, String epfNo, String incomeTaxNo, BigDecimal basicSalary, ZonedDateTime createdDate, ZonedDateTime lastModifiedDate, Set<Role> rolesForLastModifiedBy, Set<User> usersForLastModifiedBy, Set<UserRole> userRolesForLastModifiedBy, Set<UserRole> userRolesForUsername, Set<User> usersForCreatedBy, Set<Image> imagesForCreatedBy, Set<Role> rolesForCreatedBy, Set<Image> imagesForLastModifiedBy) {
       this.username = username;
       this.department = department;
       this.gender = gender;
       this.image = image;
       this.maritalStatus = maritalStatus;
       this.race = race;
       this.socsoStatus = socsoStatus;
       this.userByLastModifiedBy = userByLastModifiedBy;
       this.userByCreatedBy = userByCreatedBy;
       this.fullName = fullName;
       this.password = password;
       this.locked = locked;
       this.address = address;
       this.phoneCell = phoneCell;
       this.phoneOffice = phoneOffice;
       this.dataOfBirth = dataOfBirth;
       this.dataJoined = dataJoined;
       this.jobTitle = jobTitle;
       this.qualificationAcademic = qualificationAcademic;
       this.qualificationProfessional = qualificationProfessional;
       this.socsoNo = socsoNo;
       this.epfNo = epfNo;
       this.incomeTaxNo = incomeTaxNo;
       this.basicSalary = basicSalary;
       this.createdDate = createdDate;
       this.lastModifiedDate = lastModifiedDate;
       this.rolesForLastModifiedBy = rolesForLastModifiedBy;
       this.usersForLastModifiedBy = usersForLastModifiedBy;
       this.userRolesForLastModifiedBy = userRolesForLastModifiedBy;
       this.userRolesForUsername = userRolesForUsername;
       this.usersForCreatedBy = usersForCreatedBy;
       this.imagesForCreatedBy = imagesForCreatedBy;
       this.rolesForCreatedBy = rolesForCreatedBy;
       this.imagesForLastModifiedBy = imagesForLastModifiedBy;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=20)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="department_id")
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gender_id")
    public Gender getGender() {
        return this.gender;
    }
    
    public void setGender(Gender gender) {
        this.gender = gender;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="image_id")
    public Image getImage() {
        return this.image;
    }
    
    public void setImage(Image image) {
        this.image = image;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="marital_status_id")
    public MaritalStatus getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(MaritalStatus maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="race_id")
    public Race getRace() {
        return this.race;
    }
    
    public void setRace(Race race) {
        this.race = race;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="socso_status_id")
    public SocsoStatus getSocsoStatus() {
        return this.socsoStatus;
    }
    
    public void setSocsoStatus(SocsoStatus socsoStatus) {
        this.socsoStatus = socsoStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="last_modified_by")
    @org.springframework.data.annotation.LastModifiedBy
    public User getUserByLastModifiedBy() {
        return this.userByLastModifiedBy;
    }
    
    public void setUserByLastModifiedBy(User userByLastModifiedBy) {
        this.userByLastModifiedBy = userByLastModifiedBy;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="created_by")
    @org.springframework.data.annotation.CreatedBy
    public User getUserByCreatedBy() {
        return this.userByCreatedBy;
    }
    
    public void setUserByCreatedBy(User userByCreatedBy) {
        this.userByCreatedBy = userByCreatedBy;
    }

    
    @Column(name="full_name", nullable=false, length=100)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    
    @Column(name="password", nullable=false, length=60)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="locked", nullable=false)
    public boolean isLocked() {
        return this.locked;
    }
    
    public void setLocked(boolean locked) {
        this.locked = locked;
    }

    
    @Column(name="address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="phone_cell", length=20)
    public String getPhoneCell() {
        return this.phoneCell;
    }
    
    public void setPhoneCell(String phoneCell) {
        this.phoneCell = phoneCell;
    }

    
    @Column(name="phone_office", length=20)
    public String getPhoneOffice() {
        return this.phoneOffice;
    }
    
    public void setPhoneOffice(String phoneOffice) {
        this.phoneOffice = phoneOffice;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_of_birth", length=13)
    public Date getDataOfBirth() {
        return this.dataOfBirth;
    }
    
    public void setDataOfBirth(Date dataOfBirth) {
        this.dataOfBirth = dataOfBirth;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_joined", length=13)
    public Date getDataJoined() {
        return this.dataJoined;
    }
    
    public void setDataJoined(Date dataJoined) {
        this.dataJoined = dataJoined;
    }

    
    @Column(name="job_title", length=100)
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    
    @Column(name="qualification_academic", length=100)
    public String getQualificationAcademic() {
        return this.qualificationAcademic;
    }
    
    public void setQualificationAcademic(String qualificationAcademic) {
        this.qualificationAcademic = qualificationAcademic;
    }

    
    @Column(name="qualification_professional", length=100)
    public String getQualificationProfessional() {
        return this.qualificationProfessional;
    }
    
    public void setQualificationProfessional(String qualificationProfessional) {
        this.qualificationProfessional = qualificationProfessional;
    }

    
    @Column(name="socso_no", length=20)
    public String getSocsoNo() {
        return this.socsoNo;
    }
    
    public void setSocsoNo(String socsoNo) {
        this.socsoNo = socsoNo;
    }

    
    @Column(name="epf_no", length=20)
    public String getEpfNo() {
        return this.epfNo;
    }
    
    public void setEpfNo(String epfNo) {
        this.epfNo = epfNo;
    }

    
    @Column(name="income_tax_no", length=20)
    public String getIncomeTaxNo() {
        return this.incomeTaxNo;
    }
    
    public void setIncomeTaxNo(String incomeTaxNo) {
        this.incomeTaxNo = incomeTaxNo;
    }

    
    @Column(name="basic_salary", nullable=false, precision=16)
    public BigDecimal getBasicSalary() {
        return this.basicSalary;
    }
    
    public void setBasicSalary(BigDecimal basicSalary) {
        this.basicSalary = basicSalary;
    }

    
    @Column(name="created_date", length=35)
    @org.springframework.data.annotation.CreatedDate
    public ZonedDateTime getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(ZonedDateTime createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="last_modified_date", length=35)
    @org.springframework.data.annotation.LastModifiedDate
    public ZonedDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }
    
    public void setLastModifiedDate(ZonedDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userByLastModifiedBy")
    public Set<Role> getRolesForLastModifiedBy() {
        return this.rolesForLastModifiedBy;
    }
    
    public void setRolesForLastModifiedBy(Set<Role> rolesForLastModifiedBy) {
        this.rolesForLastModifiedBy = rolesForLastModifiedBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userByLastModifiedBy")
    public Set<User> getUsersForLastModifiedBy() {
        return this.usersForLastModifiedBy;
    }
    
    public void setUsersForLastModifiedBy(Set<User> usersForLastModifiedBy) {
        this.usersForLastModifiedBy = usersForLastModifiedBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userByLastModifiedBy")
    public Set<UserRole> getUserRolesForLastModifiedBy() {
        return this.userRolesForLastModifiedBy;
    }
    
    public void setUserRolesForLastModifiedBy(Set<UserRole> userRolesForLastModifiedBy) {
        this.userRolesForLastModifiedBy = userRolesForLastModifiedBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userByUsername")
    public Set<UserRole> getUserRolesForUsername() {
        return this.userRolesForUsername;
    }
    
    public void setUserRolesForUsername(Set<UserRole> userRolesForUsername) {
        this.userRolesForUsername = userRolesForUsername;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userByCreatedBy")
    public Set<User> getUsersForCreatedBy() {
        return this.usersForCreatedBy;
    }
    
    public void setUsersForCreatedBy(Set<User> usersForCreatedBy) {
        this.usersForCreatedBy = usersForCreatedBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userByCreatedBy")
    public Set<Image> getImagesForCreatedBy() {
        return this.imagesForCreatedBy;
    }
    
    public void setImagesForCreatedBy(Set<Image> imagesForCreatedBy) {
        this.imagesForCreatedBy = imagesForCreatedBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userByCreatedBy")
    public Set<Role> getRolesForCreatedBy() {
        return this.rolesForCreatedBy;
    }
    
    public void setRolesForCreatedBy(Set<Role> rolesForCreatedBy) {
        this.rolesForCreatedBy = rolesForCreatedBy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userByLastModifiedBy")
    public Set<Image> getImagesForLastModifiedBy() {
        return this.imagesForLastModifiedBy;
    }
    
    public void setImagesForLastModifiedBy(Set<Image> imagesForLastModifiedBy) {
        this.imagesForLastModifiedBy = imagesForLastModifiedBy;
    }




}


